'use client'

import React, { useState } from 'react'
import { MapPin, Droplets, Sun, Wind, ThermometerSun, ShieldAlert, Target, Hexagon, ChevronDown, ChevronUp } from 'lucide-react'
import type { FormulaLogicParagraph } from '@/lib/formula/generateFormulaLogic'

interface FormulaCardProps {
  formulaCode: string
  formulaName: string
  climateZone: string
  pathPills: string[]          // e.g. ["Lagos", "Dry", "Dryness"] — kept as mobile summary
  formulaRationale?: string
  summaryLine?: string         // generated by getFormulaSummaryLine — italic warm grey below formula name
  delayMs?: number
  logicParagraphs?: FormulaLogicParagraph[]  // replaces pills when provided
}

export default function FormulaCard({
  formulaCode,
  formulaName,
  climateZone,
  pathPills,
  formulaRationale,
  summaryLine,
  delayMs = 0,
  logicParagraphs,
  children,
}: FormulaCardProps & { children?: React.ReactNode }) {
  
  const [logicExpanded, setLogicExpanded] = useState(false)

  // Choose an icon based on climate zone keywords
  let ClimateIcon = ThermometerSun
  if (climateZone.toLowerCase().includes('humid')) ClimateIcon = Droplets
  if (climateZone.toLowerCase().includes('dry') || climateZone.toLowerCase().includes('arid')) ClimateIcon = Sun
  if (climateZone.toLowerCase().includes('cold')) ClimateIcon = Wind

  const hasLogic = logicParagraphs && logicParagraphs.length > 0

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 w-full">
      {/* LEFT COLUMN: Your Formula Card */}
      <div 
        className="bg-white dark:bg-[#1A1210] border border-gray-100 dark:border-[#3A2820] shadow-[0_2px_10px_rgba(42,15,6,0.04)] rounded-xl p-6 lg:p-8 flex flex-col justify-between gap-6 animate-slide-up opacity-0 h-full"
        style={{ animationDelay: `${delayMs}ms`, animationFillMode: 'forwards' }}
      >
        <div className="flex flex-col gap-4">
          <div>
            <h5 className="text-[11px] font-bold text-gray-400 dark:text-[#A3938C] uppercase tracking-widest mb-4 font-sans">
              Your Formula
            </h5>
            <div className="text-3xl sm:text-4xl font-bold font-mono text-toneek-brown dark:text-[#F0E6DF] tracking-tight mb-2">
              {formulaCode}
            </div>
            <p className="text-lg font-medium text-gray-800 dark:text-gray-200 font-sans mb-3">
              {formulaName}
            </p>

            {/* Formula summary line */}
            {summaryLine && (
              <p className="text-[14px] italic font-sans mb-4" style={{ color: '#8C7B72' }}>
                {summaryLine}
              </p>
            )}

            <div className="flex flex-col gap-3">
              <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-[#A3938C] bg-[#FAF8F5] dark:bg-[#261B18] px-3 py-2.5 rounded-lg inline-flex w-fit border border-gray-100 dark:border-[#3A2820]">
                <ClimateIcon size={16} className="text-toneek-amber" />
                <span className="font-semibold">Formulated for {climateZone}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Pills at the bottom of the card */}
        <div className="flex flex-row items-center flex-wrap gap-2 mt-4 pt-4 border-t border-gray-100 dark:border-[#3A2820]">
          {pathPills.map((pill, index) => (
            <React.Fragment key={pill}>
              <div className="bg-[#FAF8F5] dark:bg-toneek-amber/10 text-gray-600 dark:text-[#F0E6DF] text-[12px] font-semibold px-3 py-1.5 rounded-full whitespace-nowrap tracking-wide">
                {pill}
              </div>
            </React.Fragment>
          ))}
        </div>
      </div>

      {/* RIGHT COLUMN: Stack of Formula Logic & Review Schedule */}
      <div className="flex flex-col gap-6 h-full">
        {/* Top Card: Formula Logic */}
        <div 
          className="bg-white dark:bg-[#1A1210] border border-gray-100 dark:border-[#3A2820] shadow-[0_2px_10px_rgba(42,15,6,0.04)] rounded-xl p-6 lg:p-8 flex flex-col animate-slide-up opacity-0 flex-1"
          style={{ animationDelay: `${delayMs + 100}ms`, animationFillMode: 'forwards' }}
        >
          <h5 className="text-[11px] font-bold text-gray-400 dark:text-[#A3938C] uppercase tracking-widest mb-6 font-sans">
            Formula Logic
          </h5>

          {/* New Visual Logic Chain */}
          <div className="flex flex-col md:flex-row items-center justify-between gap-3 md:gap-2 w-full">
            {/* Node 1 */}
            <div className="flex flex-col items-center bg-white dark:bg-[#261B18] border border-toneek-amber/30 rounded-xl p-3 w-full md:flex-1 text-center shadow-sm">
              <ClimateIcon size={20} className="text-toneek-amber mb-2" />
              <span className="text-[10px] font-bold text-gray-800 dark:text-[#E8DDD8] uppercase leading-tight line-clamp-1 break-all px-1">{climateZone.replace(/_/g, ' ')}</span>
              <span className="text-[10px] text-gray-500 dark:text-[#A3938C] mt-1 truncate max-w-full">{pathPills[0] || 'Location'}</span>
            </div>

            <span className="text-toneek-amber font-bold hidden md:block">→</span>
            <span className="text-toneek-amber font-bold md:hidden">↓</span>

            {/* Node 2 */}
            <div className="flex flex-col items-center bg-white dark:bg-[#261B18] border border-toneek-amber/30 rounded-xl p-3 w-full md:flex-1 text-center shadow-sm">
              <ShieldAlert size={20} className="text-toneek-amber mb-2" />
              <span className="text-[10px] font-bold text-gray-800 dark:text-[#E8DDD8] uppercase leading-tight line-clamp-1 break-all px-1">{pathPills[1] || 'Skin Type'}</span>
              <span className="text-[10px] text-gray-500 dark:text-[#A3938C] mt-1 truncate max-w-full">Presentation</span>
            </div>

            <span className="text-toneek-amber font-bold hidden md:block">→</span>
            <span className="text-toneek-amber font-bold md:hidden">↓</span>

            {/* Node 3 */}
            <div className="flex flex-col items-center bg-white dark:bg-[#261B18] border border-toneek-amber/30 rounded-xl p-3 w-full md:flex-1 text-center shadow-sm">
              <Target size={20} className="text-toneek-amber mb-2" />
              <span className="text-[10px] font-bold text-gray-800 dark:text-[#E8DDD8] uppercase leading-tight line-clamp-1 break-all px-1">{pathPills[2] || 'Concern'}</span>
              <span className="text-[10px] text-gray-500 dark:text-[#A3938C] mt-1 truncate max-w-full">Primary Focus</span>
            </div>

            <span className="text-toneek-amber font-bold hidden md:block">→</span>
            <span className="text-toneek-amber font-bold md:hidden">↓</span>

            {/* Node 4 */}
            <div className="flex flex-col items-center bg-[#FAF8F5] dark:bg-toneek-amber/10 border border-toneek-amber rounded-xl p-3 w-full md:flex-[1.2] text-center shadow-sm">
              <Hexagon size={20} className="text-toneek-amber mb-2 fill-toneek-amber/20" />
              <span className="text-[11px] font-bold text-toneek-brown dark:text-[#F0E6DF] uppercase leading-tight">{formulaCode}</span>
              <span className="text-[9px] text-toneek-brown/80 dark:text-[#E8DDD8]/80 mt-1 max-w-[80px] md:max-w-full truncate">{formulaName.split('/')[0] || formulaName}</span>
            </div>
          </div>

          {/* Expandable Old Paragraphs */}
          <div className="mt-6">
            <button 
              onClick={() => setLogicExpanded(!logicExpanded)}
              className="flex items-center gap-2 text-[12px] font-semibold text-[#8C7B72] hover:text-[#d4a574] transition-colors"
            >
              {logicExpanded ? 'Hide formula logic' : 'Why this formula?'}
              {logicExpanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
            </button>

            {logicExpanded && hasLogic && (
              <div className="flex flex-col gap-5 mt-5 pt-5 border-t border-gray-100 dark:border-[#3A2820] animate-in fade-in slide-in-from-top-2 duration-300">
                {logicParagraphs!.map((p, i) => (
                  <div key={i} className="flex items-start gap-3">
                    <span className="flex-shrink-0 text-toneek-amber font-bold text-[14px] mt-0.5">→</span>
                    <div>
                      <p className="text-[13px] font-semibold text-gray-800 dark:text-[#E8DDD8] font-sans leading-snug">
                        {p.arrow}
                      </p>
                      {p.body && (
                        <p className="text-[12px] text-gray-500 dark:text-[#A3938C] font-sans leading-relaxed mt-1.5">
                          {p.body}
                        </p>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Bottom Card: Children (Formula Review Schedule) */}
        {children && (
          <div className="animate-slide-up opacity-0" style={{ animationDelay: `${delayMs + 200}ms`, animationFillMode: 'forwards' }}>
            {children}
          </div>
        )}
      </div>
    </div>
  )
}
